pylti1p3.exception.LtiException: Error during fetch URL http://localhost:8080/mod/lti/certs.php: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /mod/lti/certs.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x78200252ba60>: Failed to establish a new connection: [Errno 111] Connection refused'))

OJO:
- Al acceder a moodle desde el contenedor, me redirecciona al sitio de moodle (http://localhost:8080/moodle/)

**¿¿¿Cómo me monto la red y los contenedores para poder depurar y ejecutarlo??**
